# Generated by Django 4.2.1 on 2023-05-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=255)),
                ("gambar", models.CharField(max_length=255)),
                ("kategori", models.CharField(max_length=200)),
                ("deskripsi", models.TextField()),
                ("tgl_publish", models.DateField()),
                ("tgl_dibuat", models.DateField()),
            ],
        ),
    ]
