# Generated by Django 4.2.1 on 2023-05-22 06:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="blog",
            table="blog",
        ),
    ]
