# Generated by Django 4.2.1 on 2023-05-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_blog_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="gambar",
            field=models.ImageField(upload_to="foto/"),
        ),
    ]
