# Generated by Django 4.2.1 on 2023-05-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_blog_gambar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="gambar",
            field=models.ImageField(null=True, upload_to="foto/"),
        ),
    ]
